services:
    traefik:
        image: traefik:2.10
        container_name: traefik_nodejs-api
        restart: unless-stopped
        healthcheck:
            test:
                - CMD
                - traefik
                - healthcheck
            start_period: 5s
            interval: 3s
            timeout: 1s
            retries: 5
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - ./traefik.yml:/etc/traefik/traefik.yml:ro
            - ./certs/:/certs/:ro
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    default:
        name: nodejs-api
        external: true
