CREATE TABLE IF NOT EXISTS "project" (
    id SERIAL PRIMARY KEY NOT NULL,
    oid CHAR(21) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMP,
    "authorOid" CHAR(21) NOT NULL,
    FOREIGN KEY ("authorOid") REFERENCES "user"("oid")
);