services:
    app_dev:
        build:
            context: ../../
            dockerfile: local/local.Dockerfile
        command: ['make', 'dev-docker']
        container_name: nodejs-api_dev
        restart: unless-stopped
        # healthcheck:
        #     test:
        #         - CMD
        #         - curl
        #         - --fail
        #         - http://localhost:8080/status
        #     start_period: 5s
        #     interval: 3s
        #     timeout: 1s
        #     retries: 5
        env_file:
            - .dev.env
        labels:
            traefik.enable: true
            traefik.http.routers.dev.rule: Host(`nodejs-api.dev.sami.codes`)
            traefik.http.routers.dev.entrypoints: websecure
            traefik.http.routers.dev.tls: true
        expose:
            - 8080
        volumes:
            - ../../:/app
        profiles:
            - app
    postgres_dev:
        image: postgres:15-alpine
        container_name: postgres_nodejs-api_dev
        restart: unless-stopped
        healthcheck:
            test:
                - CMD
                - pg_isready
            start_period: 10s
            interval: 3s
            timeout: 1s
            retries: 5
        env_file:
            - .dev.env
        ports:
            - 5432:5432
        volumes:
            - ./db_data/postgres:/var/lib/postgresql/data
            - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql
        profiles:
            - support

networks:
    default:
        name: nodejs-api
        external: true
