services:
    app_dev:
        build:
            context: ../../
            dockerfile: local/local.Dockerfile
        command: ['make', 'dev-docker']
        container_name: nodejs-api_dev
        restart: unless-stopped
        # healthcheck:
        #     test:
        #         - CMD
        #         - curl
        #         - --fail
        #         - http://localhost:8080/status
        #     start_period: 5s
        #     interval: 3s
        #     timeout: 1s
        #     retries: 5
        env_file:
            - .dev.env
        labels:
            traefik.enable: true
            traefik.http.routers.dev.rule: Host(`nodejs-api.dev.sami.codes`)
            traefik.http.routers.dev.entrypoints: websecure
            traefik.http.routers.dev.tls: true
        expose:
            - 8080
        volumes:
            - ../../:/app
        profiles:
            - app

    mysql_dev:
        image: mysql:8
        container_name: mysql_nodejs-api_dev
        restart: unless-stopped
        healthcheck:
            test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"
            start_period: 10s
            interval: 3s
            timeout: 1s
            retries: 5
        env_file:
            - .dev.env
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
        profiles:
            - support

networks:
    default:
        name: nodejs-api
        external: true

volumes:
    mysql_data:
        name: mysql_nodejs-api_dev_data
