version: '3'

services:
    postgres:
        image: postgres:15
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - ./db_data/postgres:/var/lib/postgresql/data
            - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql
