type Query {
    status: StatusResponse!
    user(oid: ID!): User
    users: [User]
    project(oid: ID!): Project
    projects: [Project]
}

type Mutation {
    createUser(name: String!): User!
    createProject(name: String!, authorOid: ID!): Project!
}

type StatusResponse {
    project: String!
    env: String!
    version: String!
}

type User {
    oid: ID!
    name: String!
    createdAt: String!
    updatedAt: String!
    deletedAt: String

    projects: [Project]
}

type Project {
    oid: ID!
    name: String!
    createdAt: String!
    updatedAt: String!
    deletedAt: String

    authorOid: ID!
    author: User!
}
