type Query {
    status: StatusResponse!
    user(oid: ID!): User
    users: [User]
}

type Mutation {
    createUser(name: String!): User!
}

type StatusResponse {
    project: String!
    version: String!
}

type User {
    oid: ID!
    name: String!
    createdAt: String!
    updatedAt: String!
    deletedAt: String
}
